# Generated by Django 3.2.5 on 2022-03-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrer',
            new_name='Register',
        ),
    ]
